### ISSUE TITLE
publishing your equality chart(s) in a book?

### ISSUE THREAD

**Issue by getify** [dorey/JavaScript-Equality-Table#10]
I am writing a series of JS books called "You Don't Know JS", here:

https://github.com/getify/You-Dont-Know-JS

The next title, which I'm about to begin, is "Types & Grammar", and I wanted to know if you'd be willing to let me publish (with attribution, of course) an image-form of your chart(s) in the book?

The books are released CC-NC-ND 3.0 (free, non-commercial, non-derivative) online in that repo, and are then being published traditionally (print and ebook form) through O'Reilly.

If so, I'd be grateful, as I think it's a great visualization for the topic. Thanks for your time! :)

**Comment by getify** [comment]
@dorey

I don't see the license having been added, yet. Is it still OK to use the "unified" view of the chart [in my "Types & Grammar" book](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md#safely-using-implicit-coercion)?

How exactly should the image be attributed (besides the URL and your github username)?

+@bmacdonald_oreilly

**Comment by dorey** [comment]
Hi @getify , I've added a [cc license](https://github.com/dorey/JavaScript-Equality-Table/commit/b54f811832b52a3c2ba1f171790f599d02c5d2d6) . As for attribution, I'm happy with whatever. Github username + URL works for me.

**Comment by getify** [comment]
FYI: I am not sure if "non-commercial" will let me use it in a book that's for sale, unless you're going to grant an explicit exception for the YDKJS book.

**Comment by dorey** [comment]
Ok, I just copied it from the YDKJS repo's license.txt but I'm happy to change it. Let me know which license would be most appropriate for this.

**Comment by getify** [comment]
Mine has "NC" (non-commercial) because the book content is explicitly licensed (by contract) exclusively to O'Reilly. You could do the same for yours, if you wanted to grant a specific licensing option to me/O'Reilly.

------

Or you could pick one of the licenses that allows commercial works (if you want to let others besides my book use it). IANAL, so I can't recommend specifically what you should pick, but here's a helpful page listing what the license options are for CC:

https://creativecommons.org/licenses/

It seems like "BY-ND" or "BY-SA" might be good. Just let me know which way you'd like to go with it. :)
